### ISSUE TITLE
Add a last seen widget

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-analytics#102]
(If I understood correctly) we can obtain the information about the last login on a user from Matomo. Please implement a macro that would display a livetable with all users and their last login (on a column).

**Comment by snazare** [comment]
to be added in a separate page, not on the dashboard

**Comment by Farcasut** [comment]
The macro was implemented as a new "aggregator macro" that aggregates data from Matomo and creates a local cache to display the data in XWiki. The cache is updated via a scheduled job that runs every 7 days and can also be triggered manually using the Scheduler app by an admin. To configure the interval for which you want to see the users, you can set it in the admin section.
![391544064-d8bf699e-a43b-4d3b-a567-74339dbd3cc5](https://github.com/user-attachments/assets/50897820-918e-48d7-98f7-e09bdda8152d)

```html
Here is an example of how to update the Matomo tracking code to associate an ID with each user:
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* Tracker methods like "setCustomDimension" should be called before "trackPageView" */
  let userReference = document.querySelector('html').getAttribute('data-xwiki-user-reference');
  let id = userReference !== null ? userReference : 'guest';
  _paq.push(['setUserId', id]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u = "https://piwik.xwiki.com/";
    _paq.push(['setTrackerUrl', u + 'matomo.php']);
    _paq.push(['setSiteId', '34']);
    var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
    g.async = true; g.src = u + 'matomo.js'; s.parentNode.insertBefore(g, s);
  })();
</script>
<!-- End Matomo Code -->
```

The feature should be enable in 1.2

**Comment by ane-gabriela** [comment]
Last seen macro is working  and showing the last login on a user:

![Image](https://github.com/user-attachments/assets/2663f4c3-9ef6-443b-b358-b72041c31208)
