### ISSUE TITLE
Normal pages have N/A* in the No of actions

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-analytics#77]
**Prerequisites**

- XWiki 14.10+
- Created additional user
- Installed and configurated analytics pro app 1.0-rc3
- Trial license

**Steps to reproduce**

1. Login as Admin
2. Go to the Sandbox page and leave a comment or edit the page with further saving
3. Re-login but as another user
4. Re-peat the same action (comment, editing)
5. Login as Admin and check the Analytics Live data table 

**Actual result**:
The Live Data table shows N/A* for the No of actions column.

![IMDCUTG0yx](https://github.com/xwikisas/application-analytics/assets/56109799/b95d4ba6-6663-49ec-8e3e-59fb5f93e365)

**Expected result**:
Instead of N/A* value - the number of total actions is displayed.

Note:
Currently, only the pages of the application have statistics on the number of actions

**Comment by Farcasut** [comment]
@petrenkonikita112263, before I start investigating this issue, do you remember if the number of actions was displayed in the official Matomo GUI?

**Comment by petrenkonikita112263** [comment]
@Farcasut, I think it's the timing of the data synchronization. Because I see several actions from previous weeks in the live data table. But not from today; for instance, I visited Sandbox and Test Page and left a comment. also, before this, I visited the hidden page - in the Matomo server, it displays 3 number of actions, but in the live data table, N/A*

Previous week
![image](https://github.com/xwikisas/application-analytics/assets/56109799/4c15615d-e86a-4340-b1de-8f818fa27ab8)

Today's
![image](https://github.com/xwikisas/application-analytics/assets/56109799/3fb369db-7e4e-44da-947d-da1612f988e2)

![image](https://github.com/xwikisas/application-analytics/assets/56109799/7ed556b1-3a9b-4ffc-b183-14dc103f45b7)

**Comment by petrenkonikita112263** [comment]
I re-checked the live data table and still it doesn't display number of action for Sandbox and test pages from previous week.

![image](https://github.com/xwikisas/application-analytics/assets/56109799/6f0b1c67-9954-49f1-babd-7031b4fd0f67)
